### ISSUE TITLE
OSError: libbgmg.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by geneticsmcgill** [precimed/mixer#31]
Hi there,

Thanks for making such a cool program! I'm currently running into issues with the libbgmg.so file and was wondering if anyone could help? 

I keep getting the error: 
Traceback (most recent call last):
  File "precimed/mixer.py", line 18, in <module>
    libbgmg = LibBgmg(args.lib)
  File "/home/cl/software/mixer/precimed/mixer/libbgmg.py", line 28, in __init__
    self.cdll, self._lib_name = self._load_cdll(lib_name)
  File "/home/cl/software/mixer/precimed/mixer/libbgmg.py", line 464, in _load_cdll
    raise OSError(exception_message)
OSError: libbgmg.so: cannot open shared object file: No such file or directory
Failed to load BGMG shared library from `['/home/cl/software/mixer/src/build/lib/libbgmg.so', 'libbgmg.so']`. Try to add the location of `libbgmg.so` file into your PATH system variable, or to set BGMG_SHARED_LIBRARY - the specific system variable which may point to `libbgmg.so` file, including the full path.

Even though I have put the full path in my $PATH but it doesn't seem to fix the error. I've also tried reinstalling it.

**Comment by ofrei** [comment]
Could you please run these two commands and copy the output to this ticket?
```
ldd /home/cl/software/mixer/src/build/lib/libbgmg.so
file /home/cl/software/mixer/src/build/lib/libbgmg.so
```

**Comment by geneticsmcgill** [comment]
Thank you for the quick response! Here is the result below. 

**ldd /home/cl/software/mixer/src/build/lib/libbgmg.so**

	linux-vdso.so.1 (0x00007fff18a95000)
	libboost_program_options.so.1.69.0 => /home/cl/boost_1_69_0/stage/lib/libboost_program_options.so.1.69.0 (0x00007f48d9708000)
	libboost_filesystem.so.1.69.0 => /home/cl/boost_1_69_0/stage/lib/libboost_filesystem.so.1.69.0 (0x00007f48d94ed000)
	libboost_system.so.1.69.0 => /home/cl/boost_1_69_0/stage/lib/libboost_system.so.1.69.0 (0x00007f48d92eb000)
	libboost_date_time.so.1.69.0 => /home/cl/boost_1_69_0/stage/lib/libboost_date_time.so.1.69.0 (0x00007f48d90da000)
	libstdc++.so.6 => /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/lib/libstdc++.so.6 (0x00007f48d8d03000)
	libm.so.6 => /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/libm.so.6 (0x00007f48d89fe000)
	libgomp.so.1 => /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/lib/libgomp.so.1 (0x00007f48d87c8000)
	libgcc_s.so.1 => /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/libgcc_s.so.1 (0x00007f48d85b2000)
	libpthread.so.0 => /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/libpthread.so.0 (0x00007f48d8395000)
	libc.so.6 => /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/libc.so.6 (0x00007f48d7ff7000)
	librt.so.1 => /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/librt.so.1 (0x00007f48d7def000)
	/cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib64/ld-linux-x86-64.so.2 (0x00007f48d9cc1000)
	libdl.so.2 => /cvmfs/soft.computecanada.ca/nix/store/j0q2shlbxr4ga8jl4vfbisfx8csx219c-glibc-2.24/lib/libdl.so.2 (0x00007f48d7beb000)

**file /home/cl/software/mixer/src/build/lib/libbgmg.so**

/home/cl/software/mixer/src/build/lib/libbgmg.so: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, not stripped

**Comment by ofrei** [comment]
This looks as expected. 
Do you call "python mixer.py --lib /home/cl/software/mixer/src/build/lib/libbgmg.so", e.g. with full path to you libbgmg.so file? I not I suggest to this way, instead of using BGMG_SHARED_LIBRARY or PATH environmental variables. 

Also could you try starting "python" shell and running this code:
```
import ctypes
ctypes.CDLL('/home/cl/software/mixer/src/build/lib/libbgmg.so')
```

In my case the output is as follows:
```
>>> import ctypes
>>> ctypes.CDLL('/cluster/projects/nn9114k/oleksanf/github/mixer_plsa/src/build/lib/libbgmg.so')
<CDLL '/cluster/projects/nn9114k/oleksanf/github/mixer_plsa/src/build/lib/libbgmg.so', handle 1d69610 at 2b6c5dcd2350>
```
That's success - CDLL command can load libbgmg.so. 
On failure you'll get ``OSError: libbgmg.so: cannot open shared object file: No such file or directory``.

Are you trying to run mixer on your laptop or in some cluster environment?

**Comment by geneticsmcgill** [comment]
Yes I’ve tried with the full path before. I got an error when I tried the ctypes command. I am on a cluster and using a conda environment.

>>> ctypes.CDLL('/home/cl/software/mixer/src/build/lib/libbgmg.so')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lustre03/project/6004655/COMMUN/runs/cl/env/mixer/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /home/cl/software/mixer/src/build/lib/libbgmg.so)



On Jun 28, 2020, at 4:07 AM, Oleksandr Frei <notifications@github.com<mailto:notifications@github.com>> wrote:



This looks as expected.
Do you call "python mixer.py --lib /home/cl/software/mixer/src/build/lib/libbgmg.so", e.g. with full path to you libbgmg.so file? I not I suggest to this way, instead of using BGMG_SHARED_LIBRARY or PATH environmental variables.

Also could you try starting "python" shell and running this code:

import ctypes
ctypes.CDLL('/home/cl/software/mixer/src/build/lib/libbgmg.so')


In my case the output is as follows:

>>> import ctypes
>>> ctypes.CDLL('/cluster/projects/nn9114k/oleksanf/github/mixer_plsa/src/build/lib/libbgmg.so')
<CDLL '/cluster/projects/nn9114k/oleksanf/github/mixer_plsa/src/build/lib/libbgmg.so', handle 1d69610 at 2b6c5dcd2350>


That's success - CDLL command can load libbgmg.so.
On failure you'll get OSError: libbgmg.so: cannot open shared object file: No such file or directory.

Are you trying to run mixer on your laptop or in some cluster environment?

**Comment by ofrei** [comment]
@geneticsmcgill  The ```GLIBC_2.23' not found``` error is more informative. Does you cluster have ``module`` environment? I suggest to re-compile MiXeR from scratch (i.e. after a clean ``git clone``) and make a note of ``module list`` - i.e. the exact environment you've had at the point where you compile. Then, it's also important to ``module list`` when you get the ```GLIBC_2.23' not found```  error. I believe that there must be a difference between loaded modules.

Also, could you run ``module avail GCC``, ``module avail Anaconda``, ``module avail python``, ``module avail GNU`` (or, it's probably easier to run ``module avail`` and copy here what's relevant to python and GCC compiler.

Here is something relevant - the solution was to downgrade to slightly older version of python.
https://github.com/tensorflow/tensorflow/issues/28660

I've keep some unstructured notes from compiling MiXeR on different systems here -https://github.com/precimed/mixer/blob/master/src/README.md  . It's not a definitive guide to solving MiXeR compilation problems, and some of it refers to old version of MiXeR (e.g. if you see any reference to MATLAB it means the nodes are about MiXeR v1.0 or MiXeR v1.1, where the same  libbgmg.so was wrapped in MATLAB interface - which is now replaced with Python interface). Don't take these notes literally, but I hope it may come handy in debugging your problem.
