### ISSUE TITLE
Error when running fit1.

### ISSUE THREAD

**Issue by Zhangzzzzzy** [precimed/mixer#82]
I carried out the process of rep1-8, however, at rep=9-10, I met the following error report:

python3 mixer/precimed/mixer.py fit1 \
--trait1-file pycharm-community-2023.2.1/packages/Mixer/MDD.csv.gz \
--out pycharm-community-2023.2.1/packages/Mixer/result/MDD.fit.rep${REP} \
--extract pycharm-community-2023.2.1/packages/ldsc/1000G_EUR_Phase3_plink/test/test/1000G.EUR.QC.prune_maf0p05_rand2M_r2p8.rep${REP}.snps \
--bim-file pycharm-community-2023.2.1/packages/ldsc/1000G_EUR_Phase3_plink/1000G.EUR.QC.@.bim \
--ld-file pycharm-community-2023.2.1/packages/ldsc/1000G_EUR_Phase3_plink/1000G.EUR.QC.@.run4.ld \
--lib mixer/src/build/lib/libbgmg.so
INFO:root:__init__(lib_name=mixer/src/build/lib/libbgmg.so, context_id=0)
INFO:root:init_log(pycharm-community-2023.2.1/packages/Mixer/result/MDD.fit.rep10.log)
INFO:root:log_message(***********************************************************************
* mixer.py: Univariate and Bivariate Causal Mixture for GWAS
* Version 1.2.0
* (c) 2016-2020 Oleksandr Frei, Alexey A. Shadrin, Dominic Holland
* Norwegian Centre for Mental Disorders Research / University of Oslo
* Center for Multimodal Imaging and Genetics / UCSD
* GNU General Public License v3
***********************************************************************
Call: 
./mixer.py fit1 \
        --out pycharm-community-2023.2.1/packages/Mixer/result/MDD.fit.rep10 \
        --lib mixer/src/build/lib/libbgmg.so \
        --bim-file pycharm-community-2023.2.1/packages/ldsc/1000G_EUR_Phase3_plink/1000G.EUR.QC.@.bim \
        --ld-file pycharm-community-2023.2.1/packages/ldsc/1000G_EUR_Phase3_plink/1000G.EUR.QC.@.run4.ld \
        --trait1-file pycharm-community-2023.2.1/packages/Mixer/MDD.csv.gz \
        --extract pycharm-community-2023.2.1/packages/ldsc/1000G_EUR_Phase3_plink/test/test/1000G.EUR.QC.prune_maf0p05_rand2M_r2p8.rep10.snps 
)
INFO:root:__init__(lib_name=mixer/src/build/lib/libbgmg.so, context_id=0)
Traceback (most recent call last):
  File "/home/zhang/mixer/precimed/mixer.py", line 23, in <module>
    args.func(args)
  File "/home/zhang/mixer/precimed/mixer/cli.py", line 647, in execute_fit1_or_test1_parser
    results = init_results_struct(libbgmg, args)
  File "/home/zhang/mixer/precimed/mixer/cli.py", line 639, in init_results_struct
    results['options']['sum_weights'] = float(np.sum(libbgmg.weights))
  File "/home/zhang/mixer/precimed/mixer/libbgmg.py", line 168, in weights
    return self._get_vec_impl(self.cdll.bgmg_retrieve_weights, np.float32, self.num_tag, trait=None)
  File "/home/zhang/mixer/precimed/mixer/libbgmg.py", line 410, in _get_vec_impl
    self._check_error(func(*args))
  File "/home/zhang/mixer/precimed/mixer/libbgmg.py", line 418, in _check_error
    raise RuntimeError(self.get_last_error())
RuntimeError: runtime_error:  arg <= 0

I don't know how to solve this problem and would appreciate an answer.

**Comment by Zhangzzzzzy** [comment]
I found the solution, just need to cull out the NA and 0 snp's in it, hope this helps anyone else who also has this problem.
