### ISSUE TITLE
Runtime Error in bivariate

### ISSUE THREAD

**Issue by dqq0404** [precimed/mixer#97]
Hi,
When I ran the bivariate analysis, there was an issue:
INFO:root:__init__(lib_name=.../libbgmg.so, context_id=0)
Traceback (most recent call last):
  File ".../mixer-master/precimed/mixer.py", line 23, in <module>
    args.func(args)
  File ".../mixer-master/precimed/mixer/cli.py", line 709, in execute_fit2_or_test2_parser
    libbgmg = initialize_mixer_plugin(args)
  File ".../mixer-master/precimed/mixer/cli.py", line 562, in initialize_mixer_plugin
    libbgmg.set_ld_r2_coo_from_file(chr_label, args.ld_file.replace('@', str(chr_label)))
  File ".../mixer-master/precimed/mixer/libbgmg.py", line 126, in set_ld_r2_coo_from_file
    return self._check_error(self.cdll.bgmg_set_ld_r2_coo_from_file(self._context_id, chr_label, _p2n(filename)))
  File ".../mixer-master/precimed/mixer/libbgmg.py", line 418, in _check_error
    raise RuntimeError(self.get_last_error())
RuntimeError: exception:  std::bad_alloc
Some rep@ were wrong,but others were seemed normal.
How to fix it?

**Comment by rezanurbt** [comment]
@dqq0404 Hi, I am also having this issue. Could you please tell us how did you solve it? I appreciate your consideration. Many thanks, Reza
